-- Table: public.loan

-- DROP TABLE IF EXISTS public.loan;

CREATE TABLE IF NOT EXISTS public.loan
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    amount double precision NOT NULL,
    is_issued boolean NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT loan_pkey PRIMARY KEY (id),
    CONSTRAINT uksnp5j1a5kw8r7f2kv1pxu9hp0 UNIQUE (user_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.loan
    OWNER to postgres;